//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveHour
    {
        public int Id { get; set; }
        public Nullable<int> PoolId { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.TimeSpan> OpenHour { get; set; }
        public Nullable<System.TimeSpan> CloseHour { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Pool Pool { get; set; }
    }
}
