//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysToCour
    {
        public int Id { get; set; }
        public int IdCours { get; set; }
        public int IdDays { get; set; }
        public DateTime StartHour { get; set; }
        public DateTime EndHour { get; set; }
        public bool Type { get; set; }
        public int IdPool { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Day Day { get; set; }
        public virtual Pool Pool { get; set; }
    }
}
