//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntCustomr
    {
        public int Id { get; set; }
        public Nullable<int> PoolId { get; set; }
        public Nullable<int> CustomerToPool_Id { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.TimeSpan> StartHour { get; set; }
        public Nullable<System.TimeSpan> FinishHour { get; set; }
    
        public virtual Customr_To_Pool Customr_To_Pool { get; set; }
        public virtual Pool Pool { get; set; }
    }
}
