//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SwimMoodEntities : DbContext
    {
        public SwimMoodEntities()
            : base("name=SwimMoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveHour> ActiveHours { get; set; }
        public virtual DbSet<Cours_To_Customer> Cours_To_Customer { get; set; }
        public virtual DbSet<Customr_To_Pool> Customr_To_Pool { get; set; }
        public virtual DbSet<EntCustomr> EntCustomrs { get; set; }
        public virtual DbSet<Erea> Ereas { get; set; }
        public virtual DbSet<Maneger> Manegers { get; set; }
        public virtual DbSet<Pool> Pools { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Packege> Packeges { get; set; }
        public virtual DbSet<Cour> Cours { get; set; }
    }
}
